#!/bin/sh
# hydrocodone's compile
# shell script that compiles source code opened in vim based on file extension

file=$(readlink -f "$1")
filename="${file%.*}"

while true
do
	read -s -n 1 key
	if [$key = ""]; then
		case "$file" in
			*\.rmd) echo "require(rmarkdown); render('$file', output_dir='../')" | R --vanilla ;;
			*\.tex) pdflatex "$file" ;;
			*\.md) pandoc "$file" -o "$filename".pdf ;;
			*\.c) cc $file && ./a.out ;;
			*\.py) python $file ;;
			*\.scm) mit-scheme < "$file" ;;
			*\.r) Rscript $file
		esac
	fi
done

cd "$(pwd)" || exit
