#!/bin/bash
# hydrocodone's lock
# sets lockscreen using i3lock-color
# Dependency: i3lock-color (AUR)

i3lock \
-k \
--blur=10 \
--force-clock \
--indicator \
--ring-color=00000000 \
--ringwrong-color=e31616ff \
--inside-color=000000ff \
--insidever-color=000000ff \
--insidewrong-color=000000ff \
--keyhl-color=ffffffff \
--verif-text="" \
--wrong-text="" \
--noinput-text="" \
--lock-text="" \
--lockfailed-text="" \
--time-color=ffffffff \
--date-color=ffffffff \
--date-str="%B %d, %Y" \
--line-color=ffffffff
