#!/bin/bash
# hydrocodone's lock
# sets lockscreen using i3lock-color
# Dependency: i3lock-color (AUR)

i3lock \
-k \
--blur=10 \
--force-clock \
--indicator \
--ringcolor=00000000 \
--ringwrongcolor=e31616ff \
--insidecolor=000000ff \
--insidevercolor=000000ff \
--insidewrongcolor=000000ff \
--keyhlcolor=ffffffff \
--veriftext="" \
--wrongtext="" \
--noinputtext="" \
--locktext="" \
--lockfailedtext="" \
--timecolor=ffffffff \
--datecolor=ffffffff \
--datestr="%B %d, %Y" \
--linecolor=ffffffff
