#!/bin/sh
# hydrocodone's syu (update script)
# dependencies: pacman-contrib
# usage: syu [country]
# options: country is set to "US" unless otherwise specified.
#          it is the two letter code defining a country.

# note: add "Include: [MIRROR_DIR]/mirrorlist" above all
# "Include: /etc/pacman.d/mirrorlist" lines in /etc/pacman.conf

# TODO: make invoked syu skip non-sudo steps
if [ $EUID != 0 ]; then
	echo "[syu]: escalating root privileges..."
	sudo "$0" "$@"
	exit $?
fi

USER=$(logname)
MIRROR_DIR="/home/$USER/.config/pacman.d/"
MIRROR_LIST="$MIRROR_DIR""mirrorlist"

if [ ! -d $MIRROR_DIR ]; then
	echo "[syu]: $MIRROR_DIR does not exist. Creating..."
	mkdir -p $MIRROR_DIR
fi

country="$1"
if [ "$country" ==  "" ]; then
	country="US"
fi
url="https://www.archlinux.org/mirrorlist/?country=${country}&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on"

echo "[syu]: updating $MIRROR_LIST..."
curl -s $url | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - > $MIRROR_LIST

echo "[syu]: installing and updating packages..."
pacman -Syu
echo "[syu]: cleaning pacman cache..."
paccache -r -k 1

# update R packages
# TODO: make this a command line option since i don't use R anymore
# echo "update.packages(repos = 'https://cloud.r-project.org/')" | sudo -B R --vanilla
